services:
  - type: web
    name: adalina
    runtime: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_PUBLIC_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: CORS_ORIGIN
        value: https://adalina-v2.onrender.com
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: SUPABASE_BUCKET
        value: ADALINA
      - key: HTTPS
        value: "true"
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
      - key: ADMIN_PASSWORD_SALT
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        value: poshuiuu
      - key: CLOUDINARY_API_KEY
        value: "219957587561457"
      - key: CLOUDINARY_API_SECRET
        sync: false
